### ISSUE TITLE
Watch-App ReadMe Review

### ISSUE THREAD

**Issue by Aquijada52** [Pyrrha-Platform/Pyrrha-Watch-App#13]

**Comment by Aquijada52** [comment]
@krook ran through and installed the needed SDKs. all went well, on step 2, the PyrrhaWatchApp project was nowhere to be found on Tizen (refer to the screenshot). By chance do you need to push that project from your local? 

<img width="1790" alt="Screen Shot 2021-07-27 at 12 33 39 PM" src="https://user-images.githubusercontent.com/84873806/127216494-001e75b4-2c9a-4854-ab72-d95403484883.png">

**Comment by krook** [comment]
You will probably need to import it as a project from your workspace (for me, I keep everything I clone in `/Users/krook/dev` so I set that as the workspace and add the project from there. Does that work for you?

**Comment by Aquijada52** [comment]
That worked! Regarding running it as a web application, I'm going to keep troubleshooting and I'll send updates.

**Comment by krook** [comment]
Great. You'll want to run it on a v5.5 Web Circle (or something to that effect). You can install it through the Device Manager.

**Comment by krook** [comment]
@Aquijada52 I updated the README based on a new Big Sur install. However, I did it by adding a project from my cloned `dev` folder into my `workspace` folder. Therefore local changes don't reflect back into my local GitHub environment. Do you currently have a setup where changes that you make in Tizen Studio show up in your local `git status`? That is, did you copy into new folder, or were you able to get Tizen to open your one and the same folder as you cloned into?

**Comment by krook** [comment]
Documentation updated.
